In [80]:
#importing packages
import numpy as np
import pandas as pd


In [81]:
#import data
data = pd.read_csv('energydata_complete.csv')
data.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [82]:
data.shape

(19735, 29)

In [83]:
#checking for nulls
data.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [93]:
#call temperature inside the livingroom T2 as X and temperature outside as T6
X = data['T2']
y = data['T6']

In [94]:
from sklearn.linear_model import LinearRegression

In [95]:
X

0        19.200000
1        19.200000
2        19.200000
3        19.200000
4        19.200000
           ...    
19730    25.890000
19731    25.754000
19732    25.628571
19733    25.414000
19734    25.264286
Name: T2, Length: 19735, dtype: float64

In [101]:
#Instantiate model and fit X and y
lr = LinearRegression()
lr.fit(np.array(X).reshape(-1,1),y)

LinearRegression()

In [102]:
#Import metrics to measure performance of the linear regression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [103]:
#making prediction 
y_pred = lr.predict(np.array(X).reshape(-1,1))

In [45]:
#r2 score of predicted vs actual value
r2_score(y_pred, y)

0.4421227162483321

In [104]:
#Drop the  date and light columns
data.drop(['date', 'lights'], axis=1, inplace=True)

In [107]:
data.shape

(19735, 27)

In [108]:
#Import minmax scaler and train test split from the respective sklearn modules
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection  import train_test_split

In [109]:
min_ma = MinMaxScaler()

data_scaled = min_ma.fit_transform(data)
data_scaled = pd.DataFrame(data_scaled, columns=data.columns)

In [110]:
data_scaled

Appliances        T1      RH_1        T2      RH_2        T3      RH_3  \
0        0.046729  0.327350  0.566187  0.225345  0.684038  0.215188  0.746066   
1        0.046729  0.327350  0.541326  0.225345  0.682140  0.215188  0.748871   
2        0.037383  0.327350  0.530502  0.225345  0.679445  0.215188  0.755569   
3        0.037383  0.327350  0.524080  0.225345  0.678414  0.215188  0.758685   
4        0.046729  0.327350  0.531419  0.225345  0.676727  0.215188  0.758685   
...           ...       ...       ...       ...       ...       ...       ...   
19730    0.084112  0.926786  0.537657  0.711655  0.606309  0.830841  0.579374   
19731    0.074766  0.919747  0.536006  0.701769  0.607836  0.825302  0.582178   
19732    0.242991  0.919747  0.538666  0.692651  0.627198  0.818378  0.603988   
19733    0.383178  0.919747  0.549491  0.677054  0.634717  0.805085  0.585294   
19734    0.392523  0.919747  0.538758  0.666171  0.632902  0.799546  0.579062   

             T4      RH_4        T5  ...        T9      RH_9     T_out  \
0      0.351351  0.764262  0.175506  ...  0.223032  0.677290  0.372990   
1      0.351351  0.782437  0.175506  ...  0.226500  0.678532  0.369239   
2      0.344745  0.778062  0.175506  ...  0.219563  0.676049  0.365488   
3      0.341441  0.770949  0.175506  ...  0.219563  0.671909  0.361736   
4      0.341441  0.762697  0.178691  ...  0.219563  0.671909  0.357985   
...         ...       ...       ...  ...       ...       ...       ...   
19730  0.864865  0.765258  0.752031  ...  0.864724  0.729443  0.891747   
19731  0.864865  0.765258  0.754897  ...  0.864724  0.729443  0.887460   
19732  0.864865  0.771233  0.754897  ...  0.864724  0.729443  0.883173   
19733  0.864865  0.773794  0.752031  ...  0.864724  0.730581  0.878885   
19734  0.864865  0.781192  0.752031  ...  0.864724  0.731719  0.874598   

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
0         0.097674  0.894737   0.500000    0.953846   0.538462  0.265449   
1         0.100000  0.894737   0.476190    0.894872   0.533937  0.372083   
2         0.102326  0.894737   0.452381    0.835897   0.529412  0.572848   
3         0.104651  0.894737   0.428571    0.776923   0.524887  0.908261   
4         0.106977  0.894737   0.404762    0.717949   0.520362  0.201611   
...            ...       ...        ...         ...        ...       ...   
19730     0.602326  0.416667   0.238095    0.348718   0.901961  0.861981   
19731     0.602326  0.421053   0.250000    0.361538   0.900452  0.985726   
19732     0.602326  0.425439   0.261905    0.374359   0.898944  0.583979   
19733     0.602326  0.429825   0.273810    0.387179   0.897436  0.126371   
19734     0.602326  0.434211   0.285714    0.400000   0.895928  0.682391   

            rv2  
0      0.265449  
1      0.372083  
2      0.572848  
3      0.908261  
4      0.201611  
...         ...  
19730  0.861981  
19731  0.985726  
19732  0.583979  
19733  0.126371  
19734  0.682391  

[19735 rows x 27 columns]

In [111]:
#Define our dependent - y and independent variables - X
y = data_scaled['Appliances']
X = data_scaled.drop('Appliances', axis = 1)

In [112]:
#split our dataset into train and test sets in the ratio of 30 to 70%
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [113]:
#fit the linear regression model onto the train set
lr.fit(X_train, y_train)

LinearRegression()

In [114]:
#make prediction of the dependent variable using the model above
y_pred = lr.predict(X_test)

In [115]:
#calculating the mean absolute errror of the predicted value vs the actual
mean_absolute_error(y_pred, y_test)

0.050133623977429397

In [116]:
#calculating the mean squared errror of the predicted value vs the actual
mean_squared_error(y_pred, y_test)

0.007658778867195367

In [117]:
#Get square root of the mean squared error
np.sqrt(mean_squared_error(y_pred, y_test))

0.0875144494766171

In [119]:
#calculating the coefficient of determination of the predicted value vs the actual
r2_score(y_test, y_pred)

0.14890246319303535

In [120]:
#the coefficients of the linear model gives us the weight of each variable in contribution towards the overall model
lr.coef_

array([-0.00328105,  0.5535466 , -0.23617792, -0.45669795,  0.29062714,
        0.09604827,  0.028981  ,  0.02638578, -0.01565684,  0.01600579,
        0.23642491,  0.03804865,  0.01031878, -0.04461364,  0.10199505,
       -0.15759548, -0.18994077, -0.03980032, -0.32185967,  0.00683933,
       -0.07767065,  0.02918313,  0.01230661,  0.11775773,  0.0007701 ,
        0.0007701 ])

In [125]:
#get their absolutes
np.sort(abs(lr.coef_))

array([0.0007701 , 0.0007701 , 0.00328105, 0.00683933, 0.01031878,
       0.01230661, 0.01565684, 0.01600579, 0.02638578, 0.028981  ,
       0.02918313, 0.03804865, 0.03980032, 0.04461364, 0.07767065,
       0.09604827, 0.10199505, 0.11775773, 0.15759548, 0.18994077,
       0.23617792, 0.23642491, 0.29062714, 0.32185967, 0.45669795,
       0.5535466 ])

In [126]:
#call the respective column names to compare with the weights
data_scaled.columns

Index(['Appliances', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [144]:
#Now we train and fit a ridge regression model with an alpha of 0.4
from sklearn.linear_model import Ridge, Lasso

ridge = Ridge(alpha=0.4)

ridge.fit(X_train, y_train)

y_pred_rid = ridge.predict(X_test)

mean_squared_error(y_pred_rid, y_test)

#finding the root of the mean sqaured error for the ridge model to compare with the linear regression model 
np.sqrt(mean_squared_error(y_pred_rid, y_test))

0.08753385704628001

In [148]:
#fitting a lasso model of alpha 0.001
las = Lasso(alpha=0.001)

las.fit(X_train, y_train)

#check how many of its coeffie=cients are non-zero
las.coef_

array([ 0.        ,  0.01787993,  0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
       -0.00011004, -0.        , -0.        ,  0.        , -0.        ,
       -0.04955749,  0.00291176,  0.        ,  0.        , -0.        ,
       -0.        ])

In [149]:
#to get the RMSE of the lasso model
#first make a prediction
y_pred_las = las.predict(X_test)

np.sqrt(mean_squared_error(y_test, y_pred_las))

0.09358170467245137